# Конфигурация для обучения SlowFast на выбранных 14 классах

MODEL:
  NUM_CLASSES: 13       # Используем только 14 разрешённых классов
  ARCH: slowfast
  LOSS_FUNC: bce_loss
  HEAD_ACT: sigmoid
  DROPOUT_RATE: 0.5

DATA:
  NUM_FRAMES: 8
  SAMPLING_RATE: 2
  TRAIN_JITTER_SCALES: [256, 340]
  TRAIN_CROP_SIZE: 256
  TEST_CROP_SIZE: 256
  INPUT_CHANNEL_NUM: [3, 3]
  MULTI_LABEL: True
  INV_UNIFORM_SAMPLE: True
  ENSEMBLE_METHOD: max
  REVERSE_INPUT_CHANNEL: True
  PATH_TO_DATA_DIR: "data/ak/annot"   # Папка с аннотациями
  PATH_PREFIX: "data/ak/image"        # Папка с изображениями/видео

TRAIN:
  ENABLE: False
  DATASET: charades
  BATCH_SIZE: 8
  EVAL_PERIOD: 1
  CHECKPOINT_PERIOD: 1
  AUTO_RESUME: True
  CHECKPOINT_TYPE: pytorch
  CHECKPOINT_INFLATE: False

TEST:
  ENABLE: False
  DATASET: charades
  BATCH_SIZE: 8
  NUM_ENSEMBLE_VIEWS: 10
  NUM_SPATIAL_CROPS: 3
  #CHECKPOINT_FILE_PATH: "/mnt/c/qw1/Animal_Kingdom/action_recognition/code/slowfast/logs/slowfast/checkpoints/checkpoint_epoch_00186.pyth"
  CHECKPOINT_TYPE: pytorch
  SAVE_RESULTS_PATH: "./results/i3d"

SOLVER:
  BASE_LR: 0.0375
  LR_POLICY: steps_with_relative_lrs
  LRS: [1, 0.1, 0.01, 0.001, 0.0001, 0.00001]
  STEPS: [0, 41, 49]
  MAX_EPOCH: 200
  MOMENTUM: 0.9
  WEIGHT_DECAY: 0.0001
  WARMUP_EPOCHS: 4.0
  WARMUP_START_LR: 0.0001
  OPTIMIZING_METHOD: sgd

BN:
  USE_PRECISE_STATS: True
  NUM_BATCHES_PRECISE: 200
  NORM_TYPE: sync_batchnorm
  NUM_SYNC_DEVICES: 1

SLOWFAST:
  ALPHA: 4
  BETA_INV: 8
  FUSION_CONV_CHANNEL_RATIO: 2
  FUSION_KERNEL_SZ: 7

RESNET:
  ZERO_INIT_FINAL_BN: True
  WIDTH_PER_GROUP: 64
  NUM_GROUPS: 1
  DEPTH: 50
  TRANS_FUNC: bottleneck_transform
  STRIDE_1X1: False
  NUM_BLOCK_TEMP_KERNEL: [[3, 3], [4, 4], [6, 6], [3, 3]]
  SPATIAL_STRIDES: [[1, 1], [2, 2], [2, 2], [2, 2]]
  SPATIAL_DILATIONS: [[1, 1], [1, 1], [1, 1], [1, 1]]

NONLOCAL:
  LOCATION: [[[], []], [[], []], [[], []], [[], []]]
  GROUP: [[1, 1], [1, 1], [1, 1], [1, 1]]
  INSTANTIATION: dot_product

DATA_LOADER:
  NUM_WORKERS: 16
  PIN_MEMORY: True

NUM_GPUS: 1
NUM_SHARDS: 1
RNG_SEED: 0
OUTPUT_DIR: "./logs/slowfast"
LOG_MODEL_INFO: True

TENSORBOARD:
  ENABLE: False
  MODEL_VIS:
    TOPK_PREDS: 1
    COLORMAP: "Pastel2"
  # Указываем путь к файлу с именами классов (новый JSON)
  CLASS_NAMES_PATH: "/mnt/c/qw1/Animal_Kingdom/action_recognition/annotation/class_names_allowed.json"

DEMO:
  ENABLE: True
  INPUT_VIDEO: "/mnt/c/qw1/Animal_Kingdom/action_recognition/your_video.mp4"
  OUTPUT_FILE: "./logs/slowfast/demo_output.mp4"
  # Для демо также указываем путь к файлу с именами классов
  LABEL_FILE_PATH: "/mnt/c/qw1/Animal_Kingdom/action_recognition/annotation/class_names.json"
  COMMON_CLASS_THRES: 0.7
  UNCOMMON_CLASS_THRES: 0.3
  THREAD_ENABLE: False
  NUM_VIS_INSTANCES: 2
  VIS_MODE: "thres"
  COMMON_CLASS_NAMES: []
